steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      '${_ARTIFACT_REGION}/$PROJECT_ID/restful-api/balisnap:$SHORT_SHA', 
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_ARTIFACT_REGION}/$PROJECT_ID/restful-api/balisnap:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 
      'deploy', 
      'balisnap', 
      '--image', 
      '${_ARTIFACT_REGION}/$PROJECT_ID/restful-api/balisnap:$SHORT_SHA', 
      '--region', 
      'asia-southeast2', 
      '--platform', 
      'managed',
      '--allow-unauthenticated'
    ]
    env:
      - 'PORT=8080'
      - 'HOST=0.0.0.0'
      - 'DATABASE_URL=$$DATABASE_URL'
    secretEnv: ['DATABASE_URL']

images:
  - '${_ARTIFACT_REGION}/$PROJECT_ID/restful-api/balisnap:$SHORT_SHA'

substitutions:
  _ARTIFACT_REGION: asia-southeast2-docker.pkg.dev

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/database-url/versions/1
      env: DATABASE_URL