steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      '${_ARTIFACT_REGION}/$PROJECT_ID/restful-api/balisnap:$SHORT_SHA', 
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_ARTIFACT_REGION}/$PROJECT_ID/restful-api/balisnap:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    # args: [
    #   'run', 
    #   'deploy', 
    #   'balisnap', 
    #   '--image', 
    #   '${_ARTIFACT_REGION}/$PROJECT_ID/restful-api/balisnap:$SHORT_SHA', 
    #   '--region', 
    #   'asia-southeast2', 
    #   '--platform', 
    #   'managed',
    #   '--allow-unauthenticated'
    # ]
    args: [
      '-c',
      'gcloud run deploy balisnap
          --image ${_ARTIFACT_REGION}/$PROJECT_ID/restful-api/balisnap:$SHORT_SHA
          --region asia-southeast2
          --set-env-vars PORT=8080
          --set-env-vars HOST=0.0.0.0
          --set-env-vars DATABASE_URL=$$DATABASE_URL
          --port 8080
          --platform managed
          --allow-unauthenticated'
    ]
        
    # env:
    #   - 'PORT=8080'
    #   - 'HOST=0.0.0.0'
    secretEnv: ['DATABASE_URL']

images:
  - '${_ARTIFACT_REGION}/$PROJECT_ID/restful-api/balisnap:$SHORT_SHA'

substitutions:
  _ARTIFACT_REGION: asia-southeast2-docker.pkg.dev

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/database-url/versions/1
      env: DATABASE_URL